name: CI - Test and Push to ACR

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  IMAGE_NAME: bookstore-api

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        working-directory: bookstore-api
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        working-directory: bookstore-api
        run: pytest -q

  push:
    if: github.event_name == 'push'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Docker login to ACR (service principal)
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Build and push
        working-directory: bookstore-api
        run: |
          SHA=$(echo $GITHUB_SHA | cut -c1-7)
          IMAGE=${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}
          docker build -t $IMAGE:$SHA -t $IMAGE:latest .
          docker push $IMAGE:$SHA
          docker push $IMAGE:latest
